package com.example.campusconnect1

import com.google.firebase.firestore.DocumentId
import java.util.Date

/**
 * Model for 'users' collection in Firestore.
 */
data class User(
    val uid: String = "",
    val email: String = "",
    val fullName: String = "",
    val universityId: String = "",
    val nim: String = "",
    val verified: Boolean = false, // Must match Firestore field name
    val interests: List<String> = emptyList(),
    val profilePictureUrl: String = ""
)

/**
 * Model for 'posts' collection in Firestore.
 */
data class Post(
    // 👇 TAMBAHKAN ANOTASI INI
    // Ini akan otomatis mengisi postId dengan ID Dokumen Firestore (misal: "AutoGeneratedID123")
    @DocumentId
    val postId: String = "",
    val authorId: String = "",
    val authorName: String = "",
    val authorAvatarUrl: String = "",
    val universityId: String = "",
    val text: String = "",
    val imageUrl: String? = null,

    // Using standard Java Date for manual timestamp handling
    val timestamp: Date? = null,

    val voteCount: Int = 0,
    val commentCount: Int = 0,

    // 👇 NEW FIELD: List of User IDs who liked this post
    // Used to prevent double voting and show correct icon state
    val likedBy: List<String> = emptyList()
)

data class Comment(
    val commentId: String = "",
    val postId: String = "",
    val authorId: String = "",
    val authorName: String = "",
    val text: String = "",
    val timestamp: Date? = null
)

data class University(
    val universityId: String = "",
    val name: String = "",
    val campusLogoUrl: String = ""
)

data class AllowedNIM(
    val nim: String = "",
    val universityId: String = "",
    val role: String = "student"
)